movie_project/movie_app/urls.py
from . import views
from django.urls import path, include


app_name='movie_app'

urlpatterns = [

    path('', views.index, name='index' ),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

movie_project/movie_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movie_app.urls") )
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

movie_project/movie_app/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

movie_project/movie_app/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc', 'year', 'img']

movie_project/movie_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from .forms import MovieForm


# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request, 'index.html',context)


def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id) #this line is to fetch the values
    return render(request,'detail.html',{'key_movie':movie})


def add_movie(request):
    if request.method == "POST":
        name=request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']

        movie=Movie(name=name, desc=desc, year=year, img=img)
        movie.save()

    return render(request,'add.html')


def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form':form, 'movie':movie})


def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect( '/')
    return render(request,'delete.html')

movie_project/templates/add.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This page is to add data</title>
</head>
<body>
{% block body %}
<h1>
    Add your movies here...!!!
</h1><br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie name"><br>
    <input type="text" name="desc" placeholder="Enter movie description"><br>
    <input type="text" name="year" placeholder="Year of release"><br>
    <input type="file" name="img" placeholder="Chose your image"><br><br>


    <input type="submit">

{% endblock %}

</body>
</html>



<!--refered from-->
<!--    name=models.CharField(max_length=250)-->
<!--    year=models.IntegerField()-->
<!--    img=models.ImageField(upload_to='gallery')-->

movie_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Movie Store
  </a>
</nav>




<!--we have to print the index contents after this so,-->
{% block body %}
{% endblock %}


</body>
</html>

movie_project/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are your sure to delete this?
    <input type="submit">
</form>

movie_project/templates/detail.html
{% extends 'base.html' %}
{% block body %}


<h1>{{key_movie.name}}</h1><br>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{key_movie.img.url}}" width="250" height="300">

    <div class="col-md-6">
        <h5>{{key_movie.desc}}</h5>
        <h6><u>{{key_movie.year}}</u></h6>
        <a  class="btn btn-warning" href="{% url 'movie_app:update' key_movie.id %}"><b>Update</b></a>
        <a  class="btn btn-danger" href="{% url 'movie_app:delete' key_movie.id %}"><b>Delete</b></a>

    </div>
        </div>
    </div>
</div>



{% endblock %}

movie_project/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">



</form>

movie_project/templates/index.html
<!--calling base.html page-->
{% extends 'base.html' %}

{% block body %}

<h1 ><b>Our collections</b></h1>


<div class="container">
    <div class = "row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movie_app:detail' i.id %}" class="btn btn-primary">More</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>

</div>

{% endblock %}